### ISSUE TITLE
Plans for extract/inline refactorings?

### ISSUE THREAD

**Issue by mdwhatcott** [godoctor/godoctor#12]
I'm wondering if there are plans within the scope of this project for the following refactorings:
- Extract local variable, package variable, const, or struct field from expression
- Extract function or method from a group of statements/expressions
- Inline variable or const or field
- Inline function or method

**Comment by joverbey** [comment]
Hi Michael,

Extract Function is our highest priority; we're actually avoiding a release until this is ready. The code is currently in a branch.

Extract Local Variable is also in a branch. A student worked on it last summer, but I don't believe anyone else has seriously tested it. The code needs some cleanup, if I remember correctly.

There are no plans for the others, due to time/resources. If you're interested in contributing, we'll be more than happy to advise!

**Comment by joverbey** [comment]
The Extract Function refactoring is merged into master.

**Comment by mdwhatcott** [comment]
Awesome! I'll check it out. Thanks!

**Comment by mdwhatcott** [comment]
This looks great.

**Comment by joverbey** [comment]
Thanks!  If you try it out, please keep us posted if you find issues.  We're hoping to (finally) do a soft release later this summer.  I'm getting the Web site and stuff together now.

**Comment by joverbey** [comment]
BTW we'll probably merge Extract Local Variable into master within the next few weeks.  It's in a branch at the moment.

Gonna go ahead and close this issue for now.  We'll definitely keep the other extract/inline possibilities in mind.  Now that we have some infrastructure for them, the others might not be too bad to implement.  Just need to find time... :)
